# Generated by Django 4.2.6 on 2023-10-18 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0005_pais_estado_cidade_estado'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='estado',
            options={'ordering': ('nome',)},
        ),
        migrations.AlterModelOptions(
            name='pais',
            options={'verbose_name': 'País', 'verbose_name_plural': 'Países'},
        ),
    ]
