version: '3.5'

services:

  app:
    build: .
    ports:
      - "8001:8000"
    volumes:
      - .:/code
    entrypoint: ['sh', 'run-django.sh']
    depends_on:
      - db_prod

  db_prod:
    image: mdillon/postgis:latest
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_DB: sidia
    ports:
      - "5434:5432"
    volumes:
      - sidia-data-prod:/var/lib/postgresql/data

volumes:
  sidia-data-prod: